language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t joeattah1/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true joeattah1/react-test npm test

after_success:
  - docker build -t joeattah1/multi-client ./client
  - docker build -t joeattah1/multi-nginx ./nginx
  - docker build -t joeattah1/multi-server ./server
  - docker build -t joeattah1/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take build images and push to docker hub
  - docker push joeattah1/multi-client
  - docker push joeattah1/multi-nginx
  - docker push joeattah1/multi-server
  - docker push joeattah1/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-934217986071
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_ACCESS_KEY
